import setuptools

setuptools.setup(
    name='RL4CRN',
    version='1.0',
    description='A package for generating CRNs using different reinforcement learning algorithms.',
    author=['Maurice Filo', 'Nicolo Rossi', 'Zhou Fang'],
    author_email=['maurice.filo@bsse.ethz.ch', 'nicolo.rossi@bsse.ethz.ch', 'zhfang@amss.ac.cn'],
    install_requires=[
        'wheel',
        'torch',
        'gymnasium',
        'numpy',
        'matplotlib',
        'tqdm',
        'scipy',
        'openpyxl',
        'pytorch_lightning',
        'comet-ml',
        'torchrl',
        'networkx',
        'seaborn',
        'joblib',
        'scikit-learn',
        'scikit-sundae',
        'python-louvain',
        'cloudpickle',
    ],
    packages=setuptools.find_packages(),
    extras_require={
        "docs": [
            "mkdocs==1.6.1",
            "mkdocs-autorefs==1.4.3",
            "mkdocs-gen-files==0.6.0",
            "mkdocs-get-deps==0.2.0",
            "mkdocs-literate-nav==0.6.2",
            "mkdocs-material==9.7.1",
            "mkdocs-material-extensions==1.3.1",
            "mkdocs-section-index==0.3.10",
            "mkdocstrings==1.0.2",
            "mkdocstrings-python==2.0.1",
        ],
        "SSA": [
            'stochasticSimulations @ git+https://github.com/redsnic/stochasticApproaches.git',
        ],
    },
)